ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - packages/*
  - packages/*/playground
  - playground
  - examples/*
  - docs

catalogs:
  bundling:
    '@rollup/plugin-alias': ^6.0.0
    '@rollup/plugin-commonjs': ^29.0.0
    '@rollup/plugin-json': ^6.1.0
    '@rollup/plugin-node-resolve': ^16.0.3
    '@rollup/plugin-replace': ^6.0.3
    '@rollup/plugin-terser': ^0.4.4
    baseline-browser-mapping: ^2.10.0
    esbuild: ^0.27.3
    pathe: ^2.0.3
    rollup: ^4.59.0
    rollup-plugin-copy: ^3.5.0
    rollup-plugin-dts: ^6.3.0
    rollup-plugin-esbuild: ^6.2.1
    tinyexec: ^1.0.2
    tsdown: ^0.20.3
    vite: ^7.3.1
    vite-tsconfig-paths: ^6.1.1
  cli:
    '@antfu/eslint-config': ^7.6.0
    '@antfu/ni': ^28.2.0
    bumpp: ^10.4.1
    eslint: ^10.0.2
    eslint-plugin-format: ^2.0.1
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    pinia: ^3.0.4
    pnpm: ^10.30.2
    prettier: ^3.8.1
    rimraf: ^6.1.3
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
    vue-tsc: ^3.2.5
    wrangler: ^4.68.1
  docs:
    '@unocss/reset': ^66.6.0
    '@vueuse/core': ^14.2.1
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    unocss: ^66.6.0
    unplugin-vue-components: ^31.0.0
    vitepress: ^2.0.0-alpha.16
    vitepress-plugin-group-icons: ^1.7.1
    vitepress-plugin-mermaid: ^2.0.17
    vue: ^3.5.29
  icons:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/codicon': ^1.2.46
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/svg-spinners': ^1.2.4
  inlined:
    ansi-sequence-parser: ^1.1.3
    hast-util-from-html: ^2.0.3
    hast-util-to-html: ^9.0.5
    hast-util-to-string: ^3.0.1
    tm-grammars: ^1.31.0
    tm-themes: ^1.12.0
    vscode-oniguruma: 1.7.0
  integrations:
    lz-string: ^1.5.0
    magic-string: ^0.30.21
    markdown-exit: ^1.0.0-beta.8
    markdown-it: ^14.1.1
    markdown-it-async: ^2.2.0
    mdast-util-from-markdown: ^2.0.3
    mdast-util-gfm: ^3.1.0
    mdast-util-to-hast: ^13.2.1
    monaco-editor-core: ^0.55.1
    ohash: ^2.0.11
    rehype-raw: ^7.0.0
    rehype-stringify: ^10.0.1
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    twoslash: ^0.3.6
    twoslash-vue: ^0.3.6
    unified: ^11.0.5
    unist-util-visit: ^5.1.0
  prod:
    '@shikijs/vscode-textmate': ^10.0.2
    ansis: ^4.2.0
    cac: ^6.7.14
    oniguruma-to-es: ^4.3.4
  testing:
    '@vitest/coverage-v8': ^4.0.18
    diff-match-patch-es: ^1.0.1
    fast-glob: ^3.3.3
    fs-extra: ^11.3.3
    js-yaml: ^4.1.1
    vitest: ^4.0.18
    vitest-package-exports: ^1.2.0
  types:
    '@types/fs-extra': ^11.0.4
    '@types/hast': ^3.0.4
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it': ^14.1.2
    '@types/mdast': ^4.0.4
    '@types/node': ^25.3.0
    '@types/unist': ^3.0.3
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
